raptor_dbw_interface:
  kvaser_reader_node:
    ros__parameters:
      hardware_id: 22024
      circuit_id: 0
      bit_rate: 500000
      enable_echo: false
  kvaser_writer_node:
    ros__parameters:
      hardware_id: 22024
      circuit_id: 0
      bit_rate: 500000
      enable_echo: false

    
